server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbslide
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  profiles:
    active: api
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update